run:
  timeout: 3m
  skip-dirs:
    - internal/ent
    - internal/graph/generated
linters:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # - wsl
    # - dupl
    # - errorlint
    # - gofmt
    # - goconst
    # - revive

