name: Handle Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  tests:
    permissions:
      contents: read
      pull-requests: read
      checks: write
    uses: ./.github/workflows/tests.yaml
